{% set name = "elementpath" %}
{% set version = "5.0.3" %}
{% set sha256 = "61040ca014769d507ce19d26521a4bf1c64d2bd0776466e45030dbfe181f7062" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - elementpath

about:
  home: https://github.com/sissaschool/elementpath
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: XPath 1.0/2.0 parsers and selectors for ElementTree
  description: |
    The proposal of this package is to provide XPath 1.0, 2.0 and 3.0
    selectors for ElementTree XML data structures, both for the standard
    ElementTree library and for the lxml.etree library.

    For lxml.etree this package can be useful for providing XPath 2.0/3.0
    selectors, because lxml.etree already has it's own implementation of
    XPath 1.0.

  dev_url: https://github.com/sissaschool/elementpath

extra:
  recipe-maintainers:
    - ccwang002
